name: final_project_2023
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dependencies: any
  firebase_core: 2.4.1
  firebase_auth: ^4.2.5
  get_cli: ^0.2.30
  get: 4.6.5
  flutter: 
    sdk: flutter
  encrypted_asset_image: ^0.0.1+2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true

  
