name: final_project_2023
version: 1.0.0+1
publish_to: none
description: A new Flutter project.

environment:
  sdk: '>=3.0.2 <3.10.2'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_core_web: ^2.2.2
  firebase_auth_web: ^5.2.4
  get_cli: ^1.8.1
  showcaseview: ^2.0.0+1
  get: 4.6.5
  flutter:
    sdk: flutter
  encrypted_asset_image: ^0.0.1+2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test :
    sdk: flutter

flutter:
  uses-material-design: true
