name: final_project_2023
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  
  
  get: ^4.6.5
  
  flutter: 
    sdk: flutter
  firebase_auth: ^4.2.5
  provider: ^6.0.5
  flutter_typeahead: ^4.3.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  email_validator: ^2.1.17
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

